### ISSUE TITLE
Highlight.js assigns markdown and ruby classes for yaml files

### ISSUE THREAD

**Issue by kaankabalak** [minio/gluegun#109]
The auto detection feature of Highlight.js incorrectly highlights certain blocks of code, ideally we should have a way to pick up the argument from the `lang` attribute of the `pre` class and highlight accordingly if possible.

The following output is highlighted as a Makefile:
````
```yaml
apiVersion: v1  
kind: Pod
metadata: 
  name: prom-example
  labels:
    app: prom-example
spec:
  containers:
  - image: minio/minio
    name: minio
    args:
    - server
    - /tmp/minio
```
````

Here is the Gluegun output:
<img width="1250" alt="screen shot 2018-11-30 at 3 27 54 pm" src="https://user-images.githubusercontent.com/27314853/49320051-8e179180-f4b4-11e8-8987-aa458dced388.png">

And the following is highlighted as a Ruby file:
````
```yaml
apiVersion: v1
kind: Pod
metadata: 
  name: prom-example
  labels:
    app: prom-example
  annotations:
    prometheus.io/scrape: 'true'    # turn on scraping first
    prometheus.io/path: '/minio/prometheus/metrics'  # the URL path of the endpoint that provides metrics
    prometheus.io/scheme: 'http'              # protocol scheme of the endpoint 
    prometheus.io/port: '9000'                # port of the endpoint
spec:
  containers:
  - image: minio/minio
    name: minio
    args:
    - server
    - /tmp/minio
```
````

Here is the Gluegun output:
<img width="1238" alt="screen shot 2018-11-30 at 3 23 49 pm" src="https://user-images.githubusercontent.com/27314853/49319930-ff0a7980-f4b3-11e8-9ca0-53e5318e8de9.png">

Notice that both code blocks have the code `<pre>` tag with attribute `lang="yaml` and it should also be noted that the hljs classes are being created on the client side.
